
import "./globals.css";
import Header from "@/components/templates/Header";
import TanstackQueryProvider from "@/components/partials/provider/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";
  
import Footer from "@/components/templates/footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body >
        <TanstackQueryProvider>
          <Header />
          <div className="h-full">
          {children}

          </div>
          <footer className="">
          <Footer/>

          </footer>
          
          
        </TanstackQueryProvider>
        <Toaster/>
      </body>
    </html>
  );
}
