
import "./globals.css";
import Header from "@/components/templates/Header";
import TanstackQueryProvider from "@/components/partials/provider/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";
  




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body >
        <TanstackQueryProvider>
          <Header />
          {children}
        </TanstackQueryProvider>
        <Toaster/>
      </body>
    </html>
  );
}
