
import "./globals.css";
import Header from "@/components/templates/Header";
import TanstackQueryProvider from "@/components/partials/provider/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";
  
import Footer from "@/components/templates/footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className=" min-h-screen  " >
        <TanstackQueryProvider>
          <div className="flex flex-col min-h-screen">

          <Header />
          
         <main className="lg:flex-grow lg:mb-[12px]">
          {children}

          </main> 

          
          <footer className="w-full">
          <Footer/>

          </footer>
          
          </div>
          
        </TanstackQueryProvider>
        <Toaster/>
      </body>
    </html>
  );
}
